version: "3"

services:
  app:
    image: node:latest
    container_name: compasso-api
    restart: on-failure
    command: yarn dev
    working_dir: /app
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=docker-dev
    volumes:
      - "./:/app"
    depends_on:
      - db
    network_mode: host

  db:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./.docker:/var/lib/postgresql/data
    network_mode: host
