name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js
       uses: actions/setup-node@v1
       with:
        node-version: '14.x'

     - name: Install Dependencies
       run: yarn --frozen-lockfile

     - name: Build App
       run: yarn build

     - name: Run Test
       run: yarn test

